### ISSUE TITLE
Задачи (todo)

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#197]
- [ ] Todo в правой панели чата
- [ ] Todo организации (попап) сверху рядом с аватаром пользователя https://app.zeplin.io/project/5c20b3bcabc861afbb5cd7dd/screen/5da609cdd0f5a23073975365
- [ ] Попап tasks (добавление / обсуждение tasks) https://app.zeplin.io/project/5c20b3bcabc861afbb5cd7dd/screen/5da609ccb28781243a5baf8a\
- [ ] прикрепить todo к сообщению

**Comment by efim1382** [comment]
Сделано:
добавление задач, обновление задач, добавление комментариев к задачам, добавление фотографий в задачах.

Не сделано:
Попап
![image](https://user-images.githubusercontent.com/13278088/67765484-ef453d80-fa54-11e9-9fb3-32cc9208082d.png)
