### ISSUE TITLE
Задачи (todo)

### ISSUE THREAD

**Issue by dcversus** [uz0/chatter.io#207]
- [ ] Todo в правой панели чата
- [ ] Todo организации (попап) сверху рядом с аватаром пользователя https://app.zeplin.io/project/5c20b3bcabc861afbb5cd7dd/screen/5da609cdd0f5a23073975365
- [ ] Попап tasks (добавление / обсуждение tasks) https://app.zeplin.io/project/5c20b3bcabc861afbb5cd7dd/screen/5da609ccb28781243a5baf8a
